name = "MinimalSpanningTrees-Lean4"
version = "0.1.0"
defaultTargets = ["minimalspanningtrees-lean4"]

[[lean_lib]]
name = "MinimalSpanningTreesLean4"

[[lean_exe]]
name = "minimalspanningtrees-lean4"
root = "Main"
